#!/bin/bash

action=$1
project_root=$(dirname $(realpath $0))

shift

case $action in
    "select")
        sh $project_root/actions/select.sh $@
        ;;
    "start")
        sh $project_root/windows/all-runner.sh $(tmux display-message -p "#S") start
        ;;
    "stop")
        sh $project_root/windows/all-runner.sh $(tmux display-message -p "#S") stop
        ;;
    "restart")
        current_session=$(tmux display-message -p "#S")
        sh $project_root/windows/all-runner.sh $current_session stop
        sh $project_root/windows/all-runner.sh $current_session start
        ;;
esac
